name: Build and Export Docker Image

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: attendance-system:latest
          outputs: type=docker,dest=/tmp/attendance-system.tar

      - name: Compress image archive
        run: |
          gzip -1 /tmp/attendance-system.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-linux
          path: /tmp/attendance-system.tar.gz
          retention-days: 7